version: "3"

services:
 web:
  container_name: serviciotorneo
  restart: always
  build: .
  ports:
   - "3000:3000"
  links:
   - db

 db:
  container_name: mysqldb
  image: mysql
  environment:
   MYSQL_DATABASE: 'sa'
   MYSQL_USER: 'usuariosa'
   MYSQL_PASSWORD: '123'
   MYSQL_ROOT_PASSWORD: '123'
  ports:
   - '3306:3306'
  expose:
   - '3306'
  volumes:
   - my-db:/var/lib/mysql
  logging:
   driver: none

volumes:
 my-db:
